### ISSUE TITLE
Implement an eclipse m2e connector

### ISSUE THREAD

**Issue by mflament** [lesfurets/dOOv#26]
When using the maven generator plugin, m2e eclipse plugin complains about the unknown doov-generator mojo.
One way to get rid of this error, is to ignore the mojo execution (either in pom.xml or in eclipse project settings), but in this case, the plugin must be executed manually after the model is updated.
The m2e plugin offers an [API](http://www.eclipse.org/m2e/documentation/m2e-extension-development.html) to handle this use case.
It would allow to:  
- automatically add the generated source directory to eclipse build path when importing maven nproject
- watch for model change to relaunch the generator mojo execution

**Comment by mflament** [comment]
I have already done some quick test with the m2e plugin API. 
The issue I am currently facing is that this API only allow to monitor resources inside the same project than the  generator mojo.
And since the generator mojo relies on jar dependencies for the model, there is no easy way to trigger the generator mojo when external resource changes.
Furthermore, I am not sure if the generator mojo will then use the compiled classes located in the model project target/classes or still use the classes from model jar dependency.
It would requires to first launch the compile/package/install goals on the model project and then start the generator goal, surely making the processing too slow to be launched each time the a source code change is detected.
I understand than since the generator code (doov-generator-core) use java.lang.reflect to analyze the model content, it expect to have access to compiled classes and can not directly work  on the model source files.

I have started to look at the doov-generator-core code and I think that it could be possible to make it work on source code using a java parser (I have already used this [one](https://github.com/javaparser/javaparser) to make some code generation, it's nice and easy to use).
This would allow to integrate the generation of rules DSL directly in the model project and perhaps allow more code generation directly from the model objects (such as FieldIds, FieldTypes, FieldPaths, ...).
I am looking forward have your insight on this idea.

**Comment by gdigugli** [comment]
Hi Mark, thank you for your investigation.

You are right, dOOv currently rely on reflection to generate the 
companion classes. Reflection is quiet simple and efficient for that 
task, but for IDE support it could be painful.

It's possible to have a downstream project that use the IDE 
binary/compile folder to run dOOv. An eclipse plugin could do that 
easily but we don't provide that kind of integration.

I have a long experience with the java.lang parser (APT), and it's 
really difficult (I mean, near impossible) to introspect the generics 
types (mandatory for dOOv) and it's could be a big constraint when your 
model depends on binary deps.

At that time, it's really difficult to have dOOv working in the same 
project. There is a few options to plug post compilation tasks in maven 
and gradle. From the discussion we have with the others committers a few 
month ago, it looks like hacks with a ambiguous cases, we have that in 
mind for the road-map.

In my opinion, it encourages developers to modularize their code base, 
and having downstream module/project that use dOOv and a upstream 
project that can't. But clearly it's a constraint.

Maybe you could have a better experience with gradle. That's why we have 
migrate since dOOv 2.0. I use eclipse for my daily dev and the gradle 
integration work well in my IDE for the dOOv code base.

If you would like some help to setup your project, we are completely 
open. If you would like to contribute, you could help us to write a 
"getting started tutorial" with a real user point of view.

Have a great weekend.

G.

**Comment by dubreuia** [comment]
Reopen in new repo https://github.com/doov-io/doov/issues if necessary
